data:
  dataset: ABIDE
  atlas: cc200
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.7
  val_set: 0.1
  # time_seires: D:/Desk/Brain Graph/bestmellah/DHGFormer/abide.npy
  # smri_path: C:/Users/Lenovo/Desktop/data/abide_smri.csv
  use_smri: true
  smri_encoder_type: fcn
  # time_series_subjects_order: D:/Desk/Brain Graph/bestmellah/DHGFormer/subject_order.txt
  time_seires: /content/drive/MyDrive/DHGFormer/abide.npy
  time_series_subjects_order: /content/drive/MyDrive/DHGFormer/subject_order.txt
  smri_path: /content/drive/MyDrive/DHGFormer/abide_smri.csv
  

model:
  type: DHGFormer

  extractor_type: transformer
  embedding_size: 8
  window_size: 4

  cnn_pool_size: 16

  # product or linear
  graph_generation: product

  num_gru_layers: 4

  dropout: 0.5

  fusion_method: concat
  smri_hid_1: 500
  smri_hid_2: 30
  smri_dropout: 0.5



train:
  method: normal
  lr: 1.0e-4
  weight_decay: 1.0e-4
  epochs: 100
  optimizer: adam

  group_loss: true
  sparsity_loss: true
  sparsity_loss_weight: 1.0e-4
  log_folder: result

  # uniform or pearson
  pure_gnn_graph: pearson