data:
  dataset: ABIDE
  atlas: cc200
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.7
  val_set: 0.1
  use_smri: false
  smri_encoder_type: fcn
  use_smri_ridge_fs: false
  smri_ridge_num_features: 1435
  time_seires: /content/drive/MyDrive/DHGFormer/abide.npy
  time_series_subjects_order: /content/drive/MyDrive/DHGFormer/subject_order.txt
  smri_path: /content/drive/MyDrive/DHGFormer/abide_smri.csv
  

model:
  type: DHGFormer

  extractor_type: transformer
  embedding_size: 8
  window_size: 4

  cnn_pool_size: 16

  # product or linear
  graph_generation: product

  num_gru_layers: 4

  dropout: 0.5

  fusion_method: concat
  smri_hid_1: 500
  smri_hid_2: 30
  smri_dropout: 0.5

  use_temporal_transformer: true
  temporal_embed_dim: 16
  temporal_num_heads: 2
  temporal_num_layers: 1
  temporal_dropout: 0.3



train:
  method: normal
  lr: 1.0e-4
  weight_decay: 1.0e-4
  epochs: 100
  optimizer: adam

  group_loss: true
  sparsity_loss: true
  sparsity_loss_weight: 1.0e-4
  log_folder: result

  # uniform or pearson
  pure_gnn_graph: pearson
  val_ratio: 0.1